### ISSUE TITLE
pdf file unable to recognize

### ISSUE THREAD

**Issue by dadleo** [lamm-mit/PDF2Audio#17]
![Screenshot 2024-11-06 at 19 38 18](https://github.com/user-attachments/assets/b12445dc-e9d9-464f-b971-1836f1d9aaf2)

any pdf file uploaded, it pops up error: invalid file type. Please upload a file that is one of these formats: ['pdf'].

Any specific pdf format required?

**Comment by antenzo** [comment]
Hi @dadleo 

I'm having same issue you reported... Could you help me to resolve it?

Thanks in advance.

Regards

**Comment by dadleo** [comment]
> Hi @dadleo
> 
> I'm having same issue you reported... Could you help me to resolve it?
> 
> Thanks in advance.
> 
> Regards

You may want to check out my revision @  [PDF2Audio.ipynb](https://github.com/dadleo/PDF2Audio-w-OpenRouter-API/blob/main/PDF2Audio.ipynb).
