### ISSUE TITLE
Custom API Base

### ISSUE THREAD

**Issue by mitkox** [lamm-mit/PDF2Audio#3]
Hey, when I select "Custom API Base" on my local deployment and point it to my local Llama.cpp server it still asks for openAI API key?
I thought when selecting "openai/custom_model" it doesn't use the cloud OpenAI API but rather the local API from the llama.cpp server?

**Comment by mitkox** [comment]
I fixed it. Now works locally.

**Comment by lamm-mit** [comment]
Thanks @mitkox , glad to hear. Please post any changes you had to make or things to consider, it would be helpful for others.

**Comment by moebiussurfing** [comment]
Yes, these tweaks to use llama as a free model alternative would be cool.
